default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Energy_1559
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: space_app_development

test:
  <<: *default
  database: space_app_test

production:
  <<: *default
  database: space_app_production
  username: space_app
  password: <%= ENV['BOOK_APP_DATABASE_PASSWORD'] %>
